version: '3.8'

services:
  frontend:
    image: ghcr.io/your-username/emptymug-project-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: ghcr.io/your-username/emptymug-project-backend:latest
    ports:
      - "8000:8000"
    environment:
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USER=${EMAIL_USER:-contact@emptymug.fr}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: emptymug-network
