name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Mondays

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [frontend, backend]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner (Frontend)
      if: matrix.service == 'frontend'
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: './apps/emptymug-website/frontend'
        format: 'sarif'
        output: 'trivy-frontend.sarif'

    - name: Run Trivy vulnerability scanner (Backend)
      if: matrix.service == 'backend'
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: './apps/emptymug-website/backend'
        format: 'sarif'
        output: 'trivy-backend.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-${{ matrix.service }}.sarif'

  docker-security-scan:
    runs-on: ubuntu-latest
    needs: dependency-scan
    
    strategy:
      matrix:
        service: [frontend, backend]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image for scanning
      uses: docker/build-push-action@v5
      with:
        context: ./apps/emptymug-website/${{ matrix.service }}
        file: ./apps/emptymug-website/${{ matrix.service }}/Dockerfile
        push: false
        tags: emptymug-${{ matrix.service }}:scan
        load: true

    - name: Run Trivy vulnerability scanner on Docker image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'emptymug-${{ matrix.service }}:scan'
        format: 'sarif'
        output: 'trivy-docker-${{ matrix.service }}.sarif'

    - name: Upload Docker scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-docker-${{ matrix.service }}.sarif'
